[sdl]
fullscreen = off
fullscreen_mode = forced-borderless
window_size = 800x600
window_position = auto
pause_when_inactive = off
mute_when_inactive = off
output = opengl

[render]
aspect = auto
viewport = fit
integer_scaling = off
shader = sharp

[sblaster]
sbtype = sb16
sbbase = 220
irq = 5
dma = 1
hdma = 5
oplmode = auto
